export const styles = {
  root: { fontFamily: "'Playfair Display', Georgia, serif", background: "#f0f4e8", color: "#1a2610", minHeight: "100vh", overflowX: "hidden" },
  nav: {
    position: "fixed", top: 0, left: 0, right: 0, zIndex: 100,
    backdropFilter: "blur(12px)",
    transition: "all 0.3s ease",
    padding: "0 5%",
    display: "flex", alignItems: "center", justifyContent: "space-between",
    height: 64,
  },
  logo: { fontFamily: "'DM Sans', sans-serif", fontWeight: 400, fontSize: 24, color: "#1a2610", display: "flex", alignItems: "center", gap: 8, textDecoration: "none", letterSpacing: "-0.03em" },


  navLinks: { display: "flex", gap: 36, listStyle: "none", margin: 0, padding: 0 },
  navLink: { fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: "#3d4a2c", cursor: "pointer", transition: "color 0.2s", textDecoration: "none", letterSpacing: "0.01em" },
  btnPrimary: { background: "#1a2610", color: "#f0f4e8", border: "none", borderRadius: 6, padding: "10px 22px", fontFamily: "'DM Sans', sans-serif", fontSize: 14, fontWeight: 500, cursor: "pointer", transition: "all 0.25s ease", letterSpacing: "0.02em" },
  btnOutline: { background: "transparent", color: "#1a2610", border: "1.5px solid #1a2610", borderRadius: 6, padding: "10px 22px", fontFamily: "'DM Sans', sans-serif", fontSize: 14, fontWeight: 500, cursor: "pointer", transition: "all 0.25s ease" },
  btnGreen: { background: "#4a6741", color: "#fff", border: "none", borderRadius: 6, padding: "10px 22px", fontFamily: "'DM Sans', sans-serif", fontSize: 14, fontWeight: 500, cursor: "pointer", transition: "all 0.25s ease" },
  btnLightGreen: { background: "#d6e6c3", color: "#1a2610", border: "none", borderRadius: 6, padding: "10px 22px", fontFamily: "'DM Sans', sans-serif", fontSize: 14, fontWeight: 500, cursor: "pointer", transition: "all 0.25s ease" },
  hero: { minHeight: "100vh", display: "flex", alignItems: "center", padding: "80px 5% 60px", position: "relative", overflow: "hidden" },
  heroText: { flex: 1, maxWidth: 550 },
  heroTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(42px, 6vw, 72px)", lineHeight: 1.1, fontWeight: 700, color: "#1a2610", marginBottom: 20 },
  heroItalic: { fontStyle: "italic", fontWeight: 400 },
  heroSubtitle: { fontFamily: "'DM Sans', sans-serif", fontSize: 16, color: "#5a6a4a", lineHeight: 1.6, marginBottom: 36, maxWidth: 380 },
  heroImg: { flex: 1, display: "flex", justifyContent: "end", alignItems: "center", position: "relative" },
  heroImgEl: { width: "min(100%)", height: "min(560px, 70vh)", objectFit: "cover", borderRadius: 24, boxShadow: "0 32px 80px rgba(30,50,20,0.18)" },
  statsBar: { background: "#1a2610", padding: "36px 5%", display: "flex", alignItems: "flex-start", gap: 0, flexWrap: "wrap" },
  statItem: { flex: "1 1 120px", padding: "0 32px", borderRight: "1px solid rgba(255,255,255,0.12)", textAlign: "left" },
  statValue: { fontFamily: "'Playfair Display', serif", fontSize: 32, fontWeight: 700, color: "#fff", display: "block" },
  statLabel: { fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: "rgba(255,255,255,0.55)", marginTop: 4 },
  statsRight: { flex: 2, padding: "0 0 0 40px", fontFamily: "'DM Sans', sans-serif", fontSize: 14, color: "rgba(255,255,255,0.7)", lineHeight: 1.6 },
  section: { padding: "80px 5%" },
  sectionTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(28px, 4vw, 44px)", fontWeight: 700, color: "#1a2610", marginBottom: 12 },
  sectionSub: { fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: "#5a6a4a", lineHeight: 1.6, maxWidth: 420 },
  servicesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 32, marginTop: 52 },
  serviceCard: { padding: "0" },
  serviceIcon: { marginBottom: 16, color: "#4a6741" },
  serviceTitle: { fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 700, color: "#1a2610", marginBottom: 10 },
  serviceDesc: { fontFamily: "'DM Sans', sans-serif", fontSize: 14, color: "#5a6a4a", lineHeight: 1.7 },
  teamSection: { padding: "80px 5%", background: "#f0f4e8" },
  teamTag: { fontFamily: "'DM Sans', sans-serif", fontSize: 12, color: "#6a8a5a", letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 12 },
  teamGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 24, marginTop: 40 },
  coachCard: { background: "#1a2610", borderRadius: 16, padding: "32px 28px", color: "#fff", display: "flex", flexDirection: "column", justifyContent: "space-between", minHeight: 340 },
  coachCardTitle: { fontFamily: "'Playfair Display', serif", fontSize: 24, fontWeight: 700, color: "#fff", marginBottom: 12, marginTop: 12 },
  coachCardDesc: { fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: "rgba(255,255,255,0.65)", lineHeight: 1.6 },
  trainerCard: { borderRadius: "16px 16px 0 0", overflow: "hidden", position: "relative" },
  trainerImg: { width: "100%", height: 340, objectFit: "cover", display: "block", transition: "transform 0.5s ease" },
  trainerName: { fontFamily: "'DM Sans', sans-serif", fontSize: 14, color: "#1a2610", marginTop: 12, fontWeight: 500 },
  reviewsSection: { padding: "80px 5%", textAlign: "center" },
  reviewTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(28px, 4vw, 44px)", fontWeight: 700, color: "#1a2610", marginBottom: 8 },
  reviewGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 16, marginTop: 48 },
  reviewCard: { background: "#fff", borderRadius: 12, padding: "24px 20px", textAlign: "left", boxShadow: "0 2px 12px rgba(30,50,20,0.06)" },
  reviewerName: { fontFamily: "'DM Sans', sans-serif", fontSize: 14, fontWeight: 600, color: "#1a2610", marginBottom: 4 },
  reviewText: { fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: "#5a6a4a", lineHeight: 1.6, marginTop: 10 },
  appSection: { margin: "0 5% 80px", background: "#1a2610", borderRadius: 24, padding: "60px 8%", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 40, flexWrap: "wrap" },
  appTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(28px, 3.5vw, 42px)", fontWeight: 700, color: "#fff", lineHeight: 1.2, marginBottom: 12 },
  appItalic: { fontStyle: "italic", fontWeight: 400 },
  appDesc: { fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: "rgba(255,255,255,0.65)", marginBottom: 28 },
  storeBtns: { display: "flex", gap: 12, flexWrap: "wrap" },
  storeBtn: { background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.2)", borderRadius: 8, padding: "10px 20px", color: "#fff", fontFamily: "'DM Sans', sans-serif", fontSize: 13, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, transition: "all 0.25s ease" },
  communitySection: { padding: "80px 5%", textAlign: "center" },
  communityTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(32px, 5vw, 56px)", fontWeight: 700, color: "#1a2610", lineHeight: 1.1, marginBottom: 16 },
  communityItalic: { fontStyle: "italic", fontWeight: 400 },
  communityDesc: { fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: "#5a6a4a", maxWidth: 500, margin: "0 auto 52px" },
  plansGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 20, maxWidth: 900, margin: "0 auto" },
  planCard: { background: "#fff", borderRadius: 16, padding: "36px 32px", textAlign: "left", boxShadow: "0 4px 24px rgba(30,50,20,0.08)", transition: "transform 0.25s ease, box-shadow 0.25s ease" },
  planCardDark: { background: "#1a2610", color: "#fff" },
  planName: { fontFamily: "'DM Sans', sans-serif", fontSize: 14, color: "#6a8a5a", fontWeight: 500, marginBottom: 8, letterSpacing: "0.05em" },
  planNameDark: { color: "rgba(255,255,255,0.6)" },
  planPrice: { fontFamily: "'Playfair Display', serif", fontSize: 48, fontWeight: 700, color: "#1a2610", lineHeight: 1 },
  planPriceDark: { color: "#fff" },
  planPeriod: { fontFamily: "'DM Sans', sans-serif", fontSize: 12, color: "#8a9a7a", marginBottom: 24, marginTop: 4 },
  planDivider: { height: 1, background: "rgba(30,50,20,0.1)", margin: "24px 0" },
  planDividerDark: { background: "rgba(255,255,255,0.1)" },
  planFeature: { fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: "#5a6a4a", marginBottom: 10, display: "flex", alignItems: "center", gap: 8 },
  planFeatureDark: { color: "rgba(255,255,255,0.7)" },
  contactSection: { padding: "100px 5%", display: "flex", gap: 80, alignItems: "center", flexWrap: "wrap", justifyContent: "center" },
  contactImgs: { position: "relative", width: 440, height: 480, flexShrink: 0 },
  contactImg1: { position: "absolute", top: 0, left: 0, width: "60%", height: "65%", objectFit: "cover", borderRadius: 24, zIndex: 2, boxShadow: "0 20px 40px rgba(0,0,0,0.1)" },
  contactImg2: { position: "absolute", bottom: 0, right: 0, width: "55%", height: "55%", objectFit: "cover", borderRadius: 24, zIndex: 3, boxShadow: "0 20px 40px rgba(0,0,0,0.1)" },
  contactImg3: { position: "absolute", top: "10%", right: 0, width: "35%", height: "35%", objectFit: "cover", borderRadius: "50%", zIndex: 1 },
  contactImg4: { position: "absolute", bottom: "10%", left: "5%", width: "25%", height: "25%", objectFit: "cover", borderRadius: "50%", zIndex: 1 },
  contactForm: { flex: 1, minWidth: 320, maxWidth: 500, background: "#f9fcf5", padding: "48px 40px", borderRadius: 24, boxShadow: "0 24px 60px rgba(26,38,16,0.06)" },
  contactTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(28px, 3.5vw, 44px)", fontWeight: 700, color: "#1a2610", marginBottom: 12 },
  contactDesc: { fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: "#5a6a4a", marginBottom: 32, lineHeight: 1.6 },
  input: { width: "100%", padding: "16px 20px", fontFamily: "'DM Sans', sans-serif", fontSize: 15, border: "1px solid transparent", borderRadius: 12, background: "#fff", color: "#1a2610", outline: "none", boxSizing: "border-box", marginBottom: 16, transition: "all 0.2s ease", boxShadow: "0 4px 12px rgba(30,50,20,0.04)" },
  textarea: { width: "100%", padding: "16px 20px", fontFamily: "'DM Sans', sans-serif", fontSize: 15, border: "1px solid transparent", borderRadius: 12, background: "#fff", color: "#1a2610", outline: "none", boxSizing: "border-box", minHeight: 140, resize: "vertical", marginBottom: 24, transition: "all 0.2s ease", boxShadow: "0 4px 12px rgba(30,50,20,0.04)" },
  faqSection: { padding: "80px 5%" },
  faqTitle: { fontFamily: "'Playfair Display', serif", fontSize: "clamp(28px, 4vw, 44px)", fontWeight: 700, color: "#1a2610", marginBottom: 8 },
  faqItalic: { fontStyle: "italic" },
  faqItem: { borderBottom: "1px solid #d0d8c0", padding: "20px 0", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center" },
  faqQ: { fontFamily: "'DM Sans', sans-serif", fontSize: 15, color: "#1a2610", fontWeight: 500 },
  footer: { background: "#1a2610", padding: "60px 5% 32px", color: "rgba(255,255,255,0.7)" },
  footerGrid: { display: "grid", gridTemplateColumns: "2fr 1fr 1fr", gap: 60, marginBottom: 48, flexWrap: "wrap" },
  footerLogo: { fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 20, color: "#fff", marginBottom: 16, display: "flex", alignItems: "center", gap: 6, textDecoration: "none" },
  footerDesc: { fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: "rgba(255,255,255,0.55)", lineHeight: 1.7, maxWidth: 280, marginBottom: 24 },
  footerEmailInput: { background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 6, padding: "10px 14px", color: "#fff", fontFamily: "'DM Sans', sans-serif", fontSize: 13, width: "100%", boxSizing: "border-box", marginBottom: 10, outline: "none" },
  footerCol: { fontFamily: "'DM Sans', sans-serif" },
  footerColTitle: { fontSize: 14, fontWeight: 600, color: "#fff", marginBottom: 20 },
  footerLink: { fontSize: 13, color: "rgba(255,255,255,0.55)", marginBottom: 12, display: "block", cursor: "pointer", transition: "color 0.2s", textDecoration: "none" },
  footerBottom: { borderTop: "1px solid rgba(255,255,255,0.1)", paddingTop: 24, fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: "rgba(255,255,255,0.4)", display: "flex", justifyContent: "space-between", flexWrap: "wrap", gap: 12 },
};
